# Generated by Django 4.2.19 on 2025-03-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.IntegerField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('bio', models.TextField(max_length=100)),
            ],
        ),
    ]
